version: '3.8'

services:
  frontend:
    image: frontend-image
    ports:
      - "${FRONTEND_PORT}:80"  # Use environment variable for the frontend port
    environment:
      - BACKEND_URL=http://backend:5000  # Pass the backend URL as an environment variable
    depends_on:
      - backend

  backend:
    image: backend-image
    ports:
      - "5000:5000"